# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tyler Tringas
tagline:          'A Blog for Humans'
url:              http://www.tylertringas.com

author:
  name:           'Tyler Tringas'
  url:            https://www.tylertringas.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
